EXTENSIONS = {
    ".jpg":    "image",
    ".jpeg":   "image",
    ".png":    "image",
    ".gif":    "image",
    ".webp":   "image",
    ".svg":    "image",
    ".bmp":    "image",
    ".tif":    "image",
    ".tiff":   "image",
    ".ico":    "image",
    ".apng":   "image",
    ".avif":   "image",
    ".heic":   "image",
    ".heif":   "image",
    ".raw":    "image",
    ".jfif":   "image",

    ".mp4":    "video",
    ".mkv":    "video",
    ".avi":    "video",
    ".mov":    "video",
    ".wmv":    "video",
    ".flv":    "video",
    ".webm":   "video",
    ".mpeg":   "video",
    ".mpg":    "video",
    ".m4v":    "video",
    ".3gp":    "video",
    ".3g2":    "video",
    ".ogv":    "video",
    ".divx":   "video",
    ".xvid":   "video",

    ".mp3":    "audio",
    ".wav":    "audio",
    ".flac":   "audio",
    ".aac":    "audio",
    ".ogg":    "audio",
    ".oga":    "audio",
    ".opus":   "audio",
    ".weba":   "audio",
    ".m4a":    "audio",
    ".aiff":   "audio",
    ".aif":    "audio",
    ".au":     "audio",
    ".mid":    "audio",
    ".midi":   "audio",

    ".pdf":    "document",
    ".doc":    "document",
    ".docx":   "document",
    ".odt":    "document",
    ".rtf":    "document",
    ".txt":    "document",
    ".md":     "document",
    ".markdown": "document",

    ".epub":   "ebook",
    ".mobi":   "ebook",

    ".xls":    "spreadsheet",
    ".xlsx":   "spreadsheet",
    ".ods":    "spreadsheet",
    ".csv":    "spreadsheet",
    ".tsv":    "spreadsheet",

    ".ppt":    "presentation",
    ".pptx":   "presentation",
    ".odp":    "presentation",
    ".ppsx":   "presentation",

    ".zip":    "archive",
    ".rar":    "archive",
    ".7z":     "archive",
    ".tar":    "archive",
    ".gz":     "archive",
    ".bz":     "archive",
    ".bz2":    "archive",
    ".xz":     "archive",
    ".lz":     "archive",
    ".lzma":   "archive",
    ".lzo":    "archive",
    ".lzh":    "archive",
    ".arc":    "archive",
    ".arj":    "archive",
    ".cab":    "archive",
    ".ace":    "archive",
    ".pak":    "archive",
    ".pea":    "archive",
    ".tbz2":   "archive",
    ".txz":    "archive",
    ".alz":    "archive",
    ".egg":    "archive",

    ".iso":    "disk_image",
    ".img":    "disk_image",
    ".mds":    "disk_image",
    ".vhdx":   "disk_image",
    ".toast":  "disk_image",

    ".exe":    "executable",
    ".run":    "executable",
    ".snap":   "executable",
    ".flatpak": "executable",
    ".dll":    "executable",
    ".so":     "executable",
    ".dylib":  "executable",
    ".elf":    "executable",
    ".out":    "executable",
    ".com":    "executable",
    ".bat":    "executable",
    ".cmd":    "executable",
    ".app":    "executable",

    ".py":     "code",
    ".pyw":    "code",
    ".js":     "code",
    ".mjs":    "code",
    ".tsx":    "code",
    ".jsx":    "code",
    ".java":   "code",
    ".c":      "code",
    ".cpp":    "code",
    ".cc":     "code",
    ".cxx":    "code",
    ".h":      "code",
    ".hpp":    "code",
    ".cs":     "code",
    ".go":     "code",
    ".rs":     "code",
    ".rb":     "code",
    ".php":    "code",
    ".swift":  "code",
    ".kts":    "code",
    ".scala":  "code",
    ".lua":    "code",
    ".pm":     "code",
    ".r":      "code",
    ".sh":     "code",
    ".bash":   "code",
    ".zsh":    "code",
    ".fish":   "code",
    ".csh":    "code",
    ".psm1":   "code",
    ".vb":     "code",
    ".vbs":    "code",
    ".asm":    "code",
    ".s":      "code",
    ".f90":    "code",
    ".f95":    "code",
    ".exs":    "code",
    ".hrl":    "code",
    ".lhs":    "code",
    ".mli":    "code",
    ".nim":    "code",
    ".dart":   "code",
    ".groovy": "code",
    ".gradle": "code",
    ".hcl":    "code",
    ".html":   "code",
    ".htm":    "code",
    ".xhtml":  "code",
    ".css":    "code",
    ".scss":   "code",
    ".sass":   "code",
    ".less":   "code",
    ".webmanifest": "code",
    ".htaccess": "code",
    ".wasm":   "code",

    ".json":   "data",
    ".jsonld": "data",
    ".xml":    "data",
    ".yaml":   "data",
    ".yml":    "data",
    ".toml":   "data",
    ".ini":    "data",
    ".cfg":    "data",
    ".conf":   "data",
    ".env":    "data",
    ".properties": "data",
    ".sql":    "data",
    ".sqlite": "data",
    ".sqlite3": "data",
    ".db":     "data",
    ".dbf":    "data",

    ".ttf":    "font",
    ".otf":    "font",
    ".woff":   "font",
    ".woff2":  "font",
    ".eot":    "font",
    ".fon":    "font",
    ".pfm":    "font",

    ".stl":    "3d",
    ".obj":    "3d",
    ".fbx":    "3d",
    ".3ds":    "3d",
    ".gltf":   "3d",
    ".glb":    "3d",
    ".ply":    "3d",
    ".x3d":    "3d",
    ".amf":    "3d",
    ".3mf":    "3d",
    ".dwf":    "3d",
    ".step":   "3d",
    ".stp":    "3d",
    ".iges":   "3d",
    ".igs":    "3d",
    ".ifc":    "3d",

    ".srt":    "subtitle",
    ".ass":    "subtitle",
    ".ssa":    "subtitle",
    ".vtt":    "subtitle",
    ".sub":    "subtitle",
    ".sbv":    "subtitle",
    ".lrc":    "subtitle",

    ".bak":    "backup",
    ".bkp":    "backup",
    ".bkf":    "backup",
    ".tmp":    "backup",
    ".old":    "backup",
    ".orig":   "backup",

    ".torrent": "misc",
    ".oxps":   "misc",
    ".kmz":    "misc",
    ".log":    "misc",
    ".nfo":    "misc",
    ".diff":   "misc",
    ".patch":  "misc",
    ".pot":    "misc",
    ".mo":     "misc",
}

LEGAL_ARGS = set(EXTENSIONS.values())
LEGAL_ARGS.add("all")

COLORS = {
    "header":    "bold #d5d9d5",   
    "subheader": "#b8b8ae",       
    "text":      "#c5c9c5",      
    "index":     "#9e9b93",  
    "prompt":    "#a3bec8", 
    "success":   "#9ec49e",
    "error":     "#d4867e",
    "muted":     "#8a9389",
}
 
EXT_COLORS = {
    "video":        "#8ba4b0",
    "audio":        "#949fb5",
    "image":        "#c4b28a",
    "document":     "#c5c9c5",
    "spreadsheet":  "#87a987",
    "archive":      "#b6927b",
    "executable":   "#c4746e",
    "ebook":        "#8992a7",
    "font":         "#a6a69c",
    "subtitle":     "#7a8382",
    "3d":           "#8ea4a2",
    "disk_image":   "#a292a3",
    "presentation": "#c4b28a",
    "misc":         "#737c73",
    "all":          "bold white",
    "code":         "#4a5752",
    "data":         "#a66e5b",
    "backup":       "#e3dec3",
}
